# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            baredot
tagline:          'dead-simple dotfile management using git'
description:      'dead-simple dotfile management using <a href="https://git-scm.com/">git</a>'
#url:              http://hyde.getpoole.com
baseurl:          /

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/poole/hyde
